version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - .env:/app/.env
    restart: unless-stopped
